
# 应用服务 WEB 访问端口
server:
  port: 8083

spring:
  datasource:
    name: test
    username: root
    url: jdbc:mysql://localhost:3306/his?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 500243cq
mybatis:
  type-aliases-package: com.cq.histest.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.cq.histest.mapper: trace